name: tcpl-cpm
services:
  api:
    image: tcpl-cpm
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env
    environment:
      APP_ENV: development
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
