name: tcpl-cpm
services:
  api:
    image: tcpl-cpm
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env
    environment:
      APP_ENV: development
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "require(''http'').get(''http://localhost:4000/health/healthz'',r=>process.exit(r.statusCode===200?0:1)).on(''error'',()=>process.exit(1))"',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
