name: Docker (apps/api)

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
      - "@tcpl-cpm/api@*"

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-api-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/tcpl-cpm-api
  TURBO_SCOPE: "@tcpl-cpm/api"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          REF="${GITHUB_REF_NAME}"
          SHA_TAG=${GITHUB_SHA::7}
          TAGS="${IMAGE_NAME}:${SHA_TAG}"

          if [[ "$GITHUB_REF_TYPE" == "tag" && "$REF" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            TAGS="${IMAGE_NAME}:${REF},${IMAGE_NAME}:latest"
          fi

          if [[ "$GITHUB_REF_TYPE" == "tag" && "$REF" =~ ^@tcpl-cpm/api@([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            TAGS="${IMAGE_NAME}:v${VERSION},${IMAGE_NAME}:latest"
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build & (maybe) push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          build-args: |
            TURBO_SCOPE=${{ env.TURBO_SCOPE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
